### PR TITLE
PR to test code coverage with prowjob. Additionally PR: fixes runtime errors, includes conditional for `cleanup-oracle`

### PR DESCRIPTION
**Pull request by jcnars**
Creating this PR to validate code coverage with prowjob as outlined in the design (internal): http://go/bmx-ci:pr-triggered-test-automation.

Additionally, this PR will collect tweaks needed to fix errors faced along the testing.

### CODE REVIEW

**Comment by jcnars** [comment]
/retest

Justification for retest: added another commit:
```
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|●1…3] 
18:02 $ git commit -m "Fix relative path"
[prow-implmntn 05a5474] Fix relative path
 1 file changed, 2 insertions(+), 1 deletion(-)
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn ↑·1|…3] 
18:02 $ git push -u origin prow-implmntn
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/home/jcnarasimhan/.ssh/known_hosts).
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 357 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To git@github.com:google/bms-toolkit.git
   37edd02..05a5474  prow-implmntn -> prow-implmntn
Branch prow-implmntn set up to track remote branch prow-implmntn from origin.
```

**Comment by jcnars** [comment]
Recording here the test log for the above run: https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1501819105026510848

**Comment by jcnars** [comment]
Reason for retesting:
```bash
✘-1 ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn ↑·1|…3] 
17:02 $ git push -u origin prow-implmntn
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 622 bytes | 0 bytes/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To git@github.com:google/bms-toolkit.git
   05a5474..5cd9dd7  prow-implmntn -> prow-implmntn
Branch prow-implmntn set up to track remote branch prow-implmntn from origin.
```

**Comment by jcnars** [comment]
As expected, the proposed code change failed with:
```
TASK [host-storage : Mount Oracle user mount LV devices] ***********************
failed: [linuxserver44.orcl] (item={'purpose': 'software', 'blk_device': '/dev/mapper/sw-u01', 'name': 'u01', 'fstype': 'xfs', 'mount_point': '/u01', 'mount_opts': 'defaults'}) => {"ansible_loop_var": "item", "changed": false, "item": {"blk_device": "/dev/mapper/sw-u01", "fstype": "xfs", "mount_opts": "defaults", "mount_point": "/u01", "name": "u01", "purpose": "software"}, "msg": "value of state must be one of: absent, mounted, present, unmounted, remounted, got: created"}
failed: [linuxserver44.orcl] (item={'purpose': 'diag', 'blk_device': '/dev/mapper/sw-u02', 'name': 'u02', 'fstype': 'xfs', 'mount_point': '/u02', 'mount_opts': 'defaults'}) => {"ansible_loop_var": "item", "changed": false, "item": {"blk_device": "/dev/mapper/sw-u02", "fstype": "xfs", "mount_opts": "defaults", "mount_point": "/u02", "name": "u02", "purpose": "diag"}, "msg": "value of state must be one of: absent, mounted, present, unmounted, remounted, got: created"}
PLAY RECAP *********************************************************************
```

The corresponding log is:
https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1503884857955061760

**Comment by jcnars** [comment]
And the corresponding github checks result is as in this screenshot (internal): https://screenshot.googleplex.com/BTi8YW8S7XHk2AY

**Comment by jcnars** [comment]
Simulating a logical error.
This is the udevadm o/p for a single device:
```
[root@linuxserver44 rules.d]# udevadm info --query=all --name=/dev/mapper/3600a098038314344382b4f7539397532
P: /devices/virtual/block/dm-2
N: dm-2
L: 10
S: disk/by-id/dm-name-3600a098038314344382b4f7539397532
S: disk/by-id/dm-uuid-mpath-3600a098038314344382b4f7539397532
S: mapper/3600a098038314344382b4f7539397532
E: DEVLINKS=/dev/disk/by-id/dm-name-3600a098038314344382b4f7539397532 /dev/disk/by-id/dm-uuid-mpath-3600a098038314344382b4f7539397532 /dev/mapper/3600a098038314344382b4f7539397532
E: DEVNAME=/dev/dm-2
E: DEVPATH=/devices/virtual/block/dm-2
E: DEVTYPE=disk
E: DM_NAME=3600a098038314344382b4f7539397532
E: DM_SUSPENDED=0
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_UDEV_RULES_VSN=2
E: DM_UUID=mpath-3600a098038314344382b4f7539397532
E: MAJOR=253
E: MINOR=2
E: MPATH_SBIN_PATH=/sbin
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=25058
```

This is the code that writes out a rules file `/etc/udev/rules.d/99-oracle-asmdevices.rules`:
```
- name: (udev) Add ASM mpath disk rules on BM (udevadm info)
  become: yes
  become_user: root
  shell: udevadm info --query=all --name={{ item.1.blk_device }} | grep DM_UUID | awk -F'=' '{print $2}'
  register: udevadm_result
  when:
    - "'mapper' in item.1.blk_device"
  with_subelements:
    - "{{ asm_disks }}"
    - disks
  tags: udev_mpath
```
We will introduce a logical mistake.
We replace `DM_UUID=mpath-3600a098038314344382b4f7539397532` with `DEVPATH=/devices/virtual/block/dm-2`.

**Comment by jcnars** [comment]
Error:
```
unzip:  cannot find or open /u01/oracle_install/V982068-01.zip, /u01/oracle_install/V982068-01.zip.zip or /u01/oracle_install/V982068-01.zip.ZIP.
Warning: Permanently added '172.16.30.1' (ECDSA) to the list of known hosts.\r
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
```

**Comment by jcnars** [comment]
/test bms-toolkit-install

Reason: Familiar error of `cmd": "/sbin/mkfs.xfs -f /dev/mapper/sw-u01"` and `"mkfs.xfs: cannot open /dev/mapper/sw-u01: Device or resource busy"`

**Comment by jcnars** [comment]
The failure was caught as in the log: https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1504216949905690624


The prowjob composed the rules file  with:
```
TASK [ora-host : (udev) Add ASM mpath disk rules on BM (udev rules file)] ******
changed: [linuxserver44.orcl] => (item={'key': '/devices/virtual/block/dm-11', 'value': [{'diskgroup': 'DATA'}, {'name': 'DATA_7539397476', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397476'}]})
changed: [linuxserver44.orcl] => (item={'key': '/devices/virtual/block/dm-2', 'value': [{'diskgroup': 'DATA'}, {'name': 'DATA_7539397477', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397477'}]})
changed: [linuxserver44.orcl] => (item={'key': '/devices/virtual/block/dm-19', 'value': [{'diskgroup': 'DATA'}, {'name': 'DATA_7539397478', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397478'}]})
changed: [linuxserver44.orcl] => (item={'key': '/devices/virtual/block/dm-12', 'value': [{'diskgroup': 'DATA'}, {'name': 'DATA_7539397479', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397479'}]})
...
```

Server's udev rules file:
```
[root@linuxserver44 ~]# tail /etc/udev/rules.d/99-oracle-asmdevices.rules 
# END ASM disk udev rules for /dev/mapper/3600a098038314344382b4f7539397545
# BEGIN ASM disk udev rules for /dev/mapper/3600a098038314344382b4f7539397546
ACTION=="add|change", ENV{DM_UUID}=="/devices/virtual/block/dm-24", SYMLINK+="asmdisks/RECO_7539397546", GROUP="asmadmin", OWNER="grid", MODE="0660"
# END ASM disk udev rules for /dev/mapper/3600a098038314344382b4f7539397546
# BEGIN ASM disk udev rules for /dev/mapper/3600a098038314344382b4f7539397547
ACTION=="add|change", ENV{DM_UUID}=="/devices/virtual/block/dm-38", SYMLINK+="asmdisks/RECO_7539397547", GROUP="asmadmin", OWNER="grid", MODE="0660"
# END ASM disk udev rules for /dev/mapper/3600a098038314344382b4f7539397547
...
```

The prowjob failed with:
```
TASK [gi-setup : asm-create | (udev) Create disk groups] ***********************
failed: [linuxserver44.orcl] (item={'diskgroup': 'DATA', 'disks': [{'name': 'DATA_7539397476', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397476'}, {'name': 'DATA_7539397477', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397477'}, {'name': 'DATA_7539397478', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397478'}, {'name': 'DATA_7539397479', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397479'}, {'name': 'DATA_753939747A', 'blk_device': '/dev/mapper/3600a098038314344382b4f753939747a'}, {'name': 'DATA_7539397530', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397530'}, {'name': 'DATA_7539397531', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397531'}, {'name': 'DATA_7539397532', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397532'}, {'name': 'DATA_7539397537', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397537'}, {'name': 'DATA_7539397538', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397538'}, {'name': 'DATA_7539397539', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397539'}, {'name': 'DATA_753939752D', 'blk_device': '/dev/mapper/3600a098038314344382b4f753939752d'}, {'name': 'DATA_7539397541', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397541'}, {'name': 'DATA_7539397542', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397542'}, {'name': 'DATA_7539397543', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397543'}, {'name': 'DATA_7539397544', 'blk_device': '/dev/mapper/3600a098038314344382b4f7539397544'}]}) => {"ansible_loop_var": "item", "changed": true, "cmd": "set -o pipefail
sqlplus -s / as sysasm << EOF
CREATE DISKGROUP DATA EXTERNAL REDUNDANCY
  DISK '/dev/asmdisks/DATA_7539397476'
  DISK '/dev/asmdisks/DATA_7539397477'
...
  DISK '/dev/asmdisks/DATA_7539397544'
ATTRIBUTE
   'compatible.asm'   = '19.3.0.0.0',
   'compatible.rdbms' = ' 19.0.0.0.0';
EOF
", "delta": "0:00:01.023185", "end": "2022-03-16 15:50:29.306969", "failed_when_result": true, "item": {"diskgroup": "DATA", "disks": [{"blk_device": "/dev/mapper/3600a098038314344382b4f7539397476", "name": "DATA_7539397476"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397477", "name": "DATA_7539397477"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397478", "name": "DATA_7539397478"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397479", "name": "DATA_7539397479"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f753939747a", "name": "DATA_753939747A"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397530", "name": "DATA_7539397530"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397531", "name": "DATA_7539397531"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397532", "name": "DATA_7539397532"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397537", "name": "DATA_7539397537"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397538", "name": "DATA_7539397538"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397539", "name": "DATA_7539397539"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f753939752d", "name": "DATA_753939752D"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397541", "name": "DATA_7539397541"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397542", "name": "DATA_7539397542"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397543", "name": "DATA_7539397543"}, {"blk_device": "/dev/mapper/3600a098038314344382b4f7539397544", "name": "DATA_7539397544"}]}, "rc": 0, "start": "2022-03-16 15:50:28.283784", "stderr": "", "stderr_lines": [], "stdout": "CREATE DISKGROUP DATA EXTERNAL REDUNDANCY
*
ERROR at line 1:
ORA-15018: diskgroup cannot be created
ORA-15031: disk specification '/dev/asmdisks/DATA_7539397544' matches no disks
ORA-15031: disk specification '/dev/asmdisks/DATA_7539397543' matches no disks
...
ORA-15031: disk specification '/dev/asmdisks/DATA_7539397476' matches no disks", 
```

**Comment by jcnars** [comment]
The prowjob failure sent to github reflects as in this screenshot: https://screenshot.googleplex.com/6fTWwSyJNPQJbvA

**Comment by jcnars** [comment]
The next failure scenario simulated will be to revert the previous change and introduce the following incorrect rsp fil:

```yml
- name: Create DBCA response file script
  become: yes
  become_user: "{{ oracle_user }}"
  template:
    src: dbca.rsp.sh.j2  # ================> replace with incorrect rsp file: rac-dbca.rsp.sh.j2
    dest: "{{ swlib_unzip_path }}/dbca_{{ db_name }}.rsp.sh"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: pmon_proc.stdout == "0" and check_oratab.stdout == "0"
  tags: db-create
```

**Comment by jcnars** [comment]
Here's the incorrect simulated change (commit id https://github.com/google/bms-toolkit/pull/106/commits/40cb613c3249a983a78dd88ca84d04842d9e109f) we are hoping that will be caught by the prowjob:
```
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|✚ 1…4] 
16:47 $ cp  roles/db-create/tasks/main.yml roles/db-create/tasks/main.yml.virgin
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|✚ 1…5] 
16:48 $ vi roles/db-create/tasks/main.yml
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|✚ 2…5] 
16:48 $ git diff roles/db-create/tasks/main.yml
diff --git a/roles/db-create/tasks/main.yml b/roles/db-create/tasks/main.yml
index 3f11c63..673b452 100644
--- a/roles/db-create/tasks/main.yml
+++ b/roles/db-create/tasks/main.yml
@@ -52,7 +52,7 @@
   become: yes
   become_user: "{{ oracle_user }}"
   template:
-    src: dbca.rsp.sh.j2
+    src: rac-dbca.rsp.sh.j2
     dest: "{{ swlib_unzip_path }}/dbca_{{ db_name }}.rsp.sh"
     owner: "{{ oracle_user }}"
     group: "{{ oracle_group }}"
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|✚ 2…5] 
16:48 $ git status 
# On branch prow-implmntn
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   roles/db-create/tasks/main.yml
#	modified:   roles/ora-host/tasks/main.yml
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	logs/
#	nonrac-asm.json
#	nonrac-datamounts.json
#	roles/db-create/tasks/main.yml.virgin
#	roles/ora-host/tasks/main.yml.virgin
no changes added to commit (use "git add" and/or "git commit -a")
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|✚ 2…5] 
16:49 $ git add roles/db-create/tasks/main.yml roles/ora-host/tasks/main.yml
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn L|●2…5] 
16:49 $ git commit -m "test prowjob: introducing error in roles/db-create/tasks/main.yml rsp file (and revert roles/ora-host/tasks/main.yml)"
[prow-implmntn 40cb613] test prowjob: introducing error in roles/db-create/tasks/main.yml rsp file (and revert roles/ora-host/tasks/main.yml)
 2 files changed, 2 insertions(+), 2 deletions(-)
✔ ~/030822-prow-test-actual-impltn/bms-toolkit [prow-implmntn ↑·1|…5] 
16:50 $ git push -u origin prow-implmntn
Failed to add the RSA host key for IP address '140.82.121.3' to the list of known hosts (/home/jcnarasimhan/.ssh/known_hosts).
Counting objects: 16, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 4.08 KiB | 0 bytes/s, done.
Total 9 (delta 4), reused 2 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To git@github.com:google/bms-toolkit.git
   c887a89..40cb613  prow-implmntn -> prow-implmntn
Branch prow-implmntn set up to track remote branch prow-implmntn from origin.
```

**Comment by jcnars** [comment]
The incorrect entry added  to simulated a code regression tripped up the prowjob as follows: 

```
TASK [db-create : Run DBCA response file script] *******************************
fatal: [linuxserver44.orcl]: FAILED! => {"changed": true, "cmd": ["sh", "/u01/oracle_install/dbca_orcl.rsp.sh"], "delta": "0:00:00.003131", "end": "2022-03-16 17:47:13.267449", "msg": "non-zero return code", "rc": 127, "start": "2022-03-16 17:47:13.264318", "stderr": "/u01/oracle_install/dbca_orcl.rsp.sh: line 1: dbca: command not found", "stderr_lines": ["/u01/oracle_install/dbca_orcl.rsp.sh: line 1: dbca: command not found"], "stdout": "", "stdout_lines": []}
```

The complete prowjob (along with logfile details) is:
https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1504244544508530688

**Comment by jcnars** [comment]
The github status is as in this screenshot: https://screenshot.googleplex.com/5rotYxj98Tsbzyt

For the next round, we will revert all of the simulated failures and see if prowjob succeeds for a simulated correct code change.
This time around, for testing the successful / correct code change, we will edit the file: group_vars/all.yml so that instead of 45% of the installed RAM, we give 25% to the SGA of the DB being created.

```
# DB configuration related variables:
db_config_type: "{% if lookup('env','CLUSTER_TYPE')|default('NONE', true) in ('NONE', 'DG') %}SI{% elif lookup('env','CLUSTER_TYPE') == 'RAC' %}RAC{% endif %}"
instance_num: 1
memory_pct: 45  =========> we will change this to 25%

```

**Comment by jcnars** [comment]
/test bms-toolkit-install

change being tested: commit id: https://github.com/google/bms-toolkit/pull/106/commits/b82e66462ee1d285f121668b066a4f01dc5c1351

**Comment by jcnars** [comment]
Yup, as expected, a PR submitted that causes no code regressions passes the prowjob testing and github reports the same:
https://screenshot.googleplex.com/9NPxneppjtjSbVU

The corresponding logfile is:
https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1504264436649562112

And we can see that the SGA size is 25% of the installed, as requested in our PR:
```
[oracle@linuxserver44 ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Wed Mar 16 22:38:02 2022
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.


Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

SQL> show parameter sga

NAME				     TYPE	 VALUE
------------------------------------ ----------- ------------------------------
allow_group_access_to_sga	     boolean	 FALSE
lock_sga			     boolean	 FALSE
pre_page_sga			     boolean	 TRUE
sga_max_size			     big integer 189G
sga_min_size			     big integer 0
sga_target			     big integer 189G
unified_audit_sga_queue_size	     integer	 1048576
SQL> exit
Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

[oracle@linuxserver44 ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:            754         501         228           0          24         250
Swap:            15           0          15

[oracle@linuxserver44 ~]$ echo "754*0.25"|bc
188.50
```

**Comment by jcnars** [comment]
This was a test triggered to test no-op with @mfielding and it ran successfully.
The corresponding logfile is at:
https://oss-prow.knative.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/106/bms-toolkit-install/1506343429271982080

**Comment by jcnars** [comment]
Closing this as the project is completed.

(internal tracking: http://b/214481941 Design and actual implementation of PR triggered Test Automation for bms-toolkit repo)

**Comment by jcnars** [comment]
Reopening this PR to fix the errors as noted in PR comment:
https://github.com/google/bms-toolkit/pull/102#issuecomment-1145337946

**Review by mfielding — APPROVED** [review]

**Review by mfielding — APPROVED** [review]

**Comment by jcnars** [comment]
Holding off on merging this PR, due to a parallel prowjob running at:
https://oss.gprow.dev/view/gs/bmaas-testing-prow-bucket/pr-logs/pull/google_bms-toolkit/90/bms-toolkit-install/1533266732624384000

triggered by me to troubleshoot... triggering comment is:
https://github.com/google/bms-toolkit/pull/90#issuecomment-1146722495

**Comment by jcnars** [comment]
Triggering a parallel prowjob, just for haha to test the line `max_concurrency: 1` introduced in: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/google/bms-toolkit/bms-toolkit-presubmit.yaml#L7

**Comment by jcnars** [comment]
The other prowjob is at:
```
TASK [rdbms-setup : rdbms-install | Installer confirmations] *******************
ok: [linuxserver44.orcl] => {
    "msg": [
        "Installing from file : ['V982063-01.zip']",
        "Unzipping into dir   : /u01/app/oracle/product/19.3.0/dbhome_1",
        "Using installer dir  : /u01/app/oracle/product/19.3.0/dbhome_1"
    ]
}
TASK [rdbms-setup : rdbms-install | Set variable for OneOff patch] *************
ok: [linuxserver44.orcl]
```

And this prowjob is pending ! Neat !
https://screenshot.googleplex.com/9u8H9wtxCMkBDjL

**Comment by jcnars** [comment]
Neat, the other prowjob finished and this job is triggered automatically !

**Pull request merged**
