### PR TITLE
Fix apply-patch.sh for RAC environments

### PR DESCRIPTION
**Pull request by mfielding**
Running apply-patch.sh on a RAC env, I ran into a few issues:

* OPatch failed due to a version mismatch between nodes

```
        "Wrong OPatch software installed in following homes:",
        "Host:at-4436897-svr005, Home:/u01/app/oracle/product/19.3.0/dbhome_1",
        "",
        "Host:at-4436897-svr005, Home:/u01/app/19.3.0/grid",
        "",
        "OPATCHAUTO-72088: OPatch version check failed.",
        "OPATCHAUTO-72088: OPatch software version in homes selected for patching are different.",
        "OPATCHAUTO-72088: Please install same OPatch software in all homes.",
        "OPatchAuto failed.",
```

The cause is the ordering of tasks:  we patch the first node before patching the second node, so when we come for the first patch, opatch on the second node hasn't been updated.  To fix, I'm fplitting the first few commands, including the OPatch update, into a separate playbook that runs on all nodes, in advance of the `opatch analyze`

* opatch failure with `-rolling` argument

Running `opatchauto -rolling` produced an error:

```
TASK [rac-opatch | Run GI opatch apply] ****************************************
failed: [at-4436897-svr001] (item={u'category': u'RU', u'patchfile': u'p34449117_190000_Linux-x86-64.zip', u'upgrade': False, u'ocm': False, u'patchnum': u'34449117', u'md5sum': u'GAdowBq8IzvPAqD3wMnd/g==', u'prereq_check': False, u'base': u'19.3.0.0.0', u'release': u'19.17.0.0.221018', u'method': u'opatchauto apply', u'patch_subdir': u'/34416665'}) => {"ansible_loop_var": "patch", "changed": true, "cmd": ["/u01/app/19.3.0/grid/OPatch/opatchauto", "apply", "-rolling"], "delta": "0:00:03.102461", "end": "2023-01-06 17:46:29.412372", "msg": "non-zero return code", "patch": {"base": "19.3.0.0.0", "category": "RU", "md5sum": "GAdowBq8IzvPAqD3wMnd/g==", "method": "opatchauto apply", "ocm": false, "patch_subdir": "/34416665", "patchfile": "p34449117_190000_Linux-x86-64.zip", "patchnum": "34449117", "prereq_check": false, "release": "19.17.0.0.221018", "upgrade": false}, "rc": 42, "start": "2023-01-06 17:46:26.309911", "stderr": "", "stderr_lines": [], "stdout": "\nOPatchauto session is initiated at Fri Jan  6 17:46:26 2023\nSession log file is /u01/app/19.3.0/grid/cfgtoollogs/opatchauto/opatchauto2023-01-06_05-46-28PM.log\nOPATCHAUTO-72050: System instance creation failed.\nOPATCHAUTO-72050: Failed while retrieving system information.\nOPATCHAUTO-72050: Please check log file for more details.\nOPatchAuto failed.\n\nOPatchauto session completed at Fri Jan  6 17:46:29 2023\nTime taken to complete the session 0 minute, 3 seconds\n\n opatchauto failed with error code 42", "stdout_lines": ["", "OPatchauto session is initiated at Fri Jan  6 17:46:26 2023", "Session log file is /u01/app/19.3.0/grid/cfgtoollogs/opatchauto/opatchauto2023-01-06_05-46-28PM.log", "OPATCHAUTO-72050: System instance creation failed.", "OPATCHAUTO-72050: Failed while retrieving system information.", "OPATCHAUTO-72050: Please check log file for more details.", "OPatchAuto failed.", "", "OPatchauto session completed at Fri Jan  6 17:46:29 2023", "Time taken to complete the session 0 minute, 3 seconds", "", " opatchauto failed with error code 42"]}
```

We need to go a few files down to see the log of the boostrap (java) command.

```
2023-01-06 17:46:28,709 INFO  [1] com.oracle.glcm.patch.auto.db.util.BootstrapOptionValidator - Invalid arguments: [-rolling]
```

As per
https://docs.oracle.com/cd/E24628_01/doc.121/e39376/configuration_patching.htm#OPTCH635, rolling patching is the default, and non-rolling needs explicit `-nonrolling`.  I couldn't find any web or MOS references of a `-rolling` argument to opatch or opatchauto, so here I simply remove `-rolling` but retain `-nonrolling` when requested (which resolves the issue).

* Invalid objects after a the second run of datapatch

We run datapatch twice, but only recompile invalid objects after the first run.  I found that there were still invalid objects left after the second run of datapatch, so I added a second urltp call.

Sample output:
https://gist.github.com/mfielding/89f1a12c0b723b00e0711eaef515018c

### CODE REVIEW

**Comment by mfielding** [comment]
Updated to current HEAD, and re-ran to confirm it still works without errors: https://gist.github.com/mfielding/89f1a12c0b723b00e0711eaef515018c

**Review by alex-basinov — APPROVED** [review]

**Pull request merged**
