### PR TITLE
T-178 Added role to open listener/scan ports for RAC

### PR DESCRIPTION
**Pull request by muresan**

### CODE REVIEW

**Review by mfielding — COMMENTED** [review]
What about the case where the host has no firewall?  Given that the config should be functional in this case, I'm not sure if we want to raise a fatal error halfway through in such a case.  Maybe just a warning?

**Comment by muresan** [comment]
The intial request was to "open a firewall port for the listener in RAC as for single instance". We already open a listener port for the single instance setup, this adds a similar set of tasks to have the same ports opened but based on scan_port not on listener port.
By default, based on disable_firewall variable, we do not disable the firewall. In order for this task to not fail, I'll make it dependent on that variable so we do not try to open ports in the firewall if it's already disabled.

**Comment by muresan** [comment]
@googlebot I signed it!

**Comment by muresan** [comment]
> What about the case where the host has no firewall? Given that the config should be functional in this case, I'm not sure if we want to raise a fatal error halfway through in such a case. Maybe just a warning?

I added conditionals to ensure task is executed only when firewall is enabled. Default is firewall enabled.

**Review by mfielding — APPROVED** [review]

**Pull request merged**
